export const PROVINCES = [
  { name: "Bas-Uélé", count: 45 },
  { name: "Équateur", count: 12 },
  { name: "Haut-Katanga", count: 850 },
  { name: "Haut-Lomami", count: 34 },
  { name: "Haut-Uélé", count: 56 },
  { name: "Ituri", count: 120 },
  { name: "Kasaï", count: 43 },
  { name: "Kasaï-Central", count: 65 },
  { name: "Kasaï-Oriental", count: 88 },
  { name: "Kongo Central", count: 430 },
  { name: "Kwango", count: 21 },
  { name: "Kwilu", count: 34 },
  { name: "Lomami", count: 15 },
  { name: "Lualaba", count: 520 },
  { name: "Mai-Ndombe", count: 9 },
  { name: "Maniema", count: 27 },
  { name: "Mongala", count: 11 },
  { name: "Nord-Kivu", count: 650 },
  { name: "Nord-Ubangi", count: 14 },
  { name: "Sankuru", count: 8 },
  { name: "Sud-Kivu", count: 480 },
  { name: "Sud-Ubangi", count: 19 },
  { name: "Tanganyika", count: 76 },
  { name: "Tshopo", count: 110 },
  { name: "Tshuapa", count: 5 },
  { name: "Kinshasa", count: 1250 },
];

export const MAKES_AND_MODELS = [
  { make: "Toyota", count: 1450, models: [{ name: "Corolla", count: 14 }, { name: "RAV4", count: 58 }, { name: "Land Cruiser", count: 36 }, { name: "Hilux", count: 76 }, { name: "Camry", count: 77 }, { name: "Yaris", count: 77 }, { name: "Prado", count: 88 }, { name: "Fortuner", count: 106 }] },
  { make: "Mercedes-Benz", count: 320, models: [{ name: "C-Class", count: 51 }, { name: "E-Class", count: 97 }, { name: "G-Class", count: 34 }, { name: "GLE", count: 90 }, { name: "GLC", count: 101 }] },
  { make: "Ford", count: 210, models: [{ name: "Ranger", count: 15 }, { name: "Figo", count: 49 }, { name: "Everest", count: 78 }, { name: "F-150", count: 61 }, { name: "EcoSport", count: 20 }] },
  { make: "Hyundai", count: 430, models: [{ name: "Tucson", count: 65 }, { name: "Santa Fe", count: 40 }, { name: "Elantra", count: 33 }, { name: "Creta", count: 67 }, { name: "Accent", count: 33 }] },
  { make: "Nissan", count: 350, models: [{ name: "Patrol", count: 63 }, { name: "X-Trail", count: 20 }, { name: "Navara", count: 26 }, { name: "Hardbody", count: 47 }, { name: "Almera", count: 109 }] },
  { make: "Mitsubishi", count: 280, models: [{ name: "Pajero", count: 29 }, { name: "L200", count: 89 }, { name: "Outlander", count: 102 }, { name: "ASX", count: 89 }] },
  { make: "Kia", count: 260, models: [{ name: "Sportage", count: 54 }, { name: "Sorento", count: 105 }, { name: "Picanto", count: 31 }, { name: "Rio", count: 23 }] },
  { make: "BMW", count: 190, models: [{ name: "X5", count: 13 }, { name: "3 Series", count: 109 }, { name: "X3", count: 56 }, { name: "5 Series", count: 49 }] },
  { make: "Volkswagen", count: 210, models: [{ name: "Touareg", count: 54 }, { name: "Golf", count: 103 }, { name: "Tiguan", count: 84 }, { name: "Polo", count: 103 }, { name: "Amarok", count: 90 }] },
  { make: "Lexus", count: 150, models: [{ name: "RX 350", count: 83 }, { name: "LX 570", count: 15 }, { name: "IS 250", count: 65 }, { name: "GX 460", count: 14 }] },
  { make: "Suzuki", count: 140, models: [{ name: "Grand Vitara", count: 100 }, { name: "Swift", count: 70 }, { name: "Jimny", count: 49 }, { name: "Alto", count: 107 }] },
  { make: "Land Rover", count: 130, models: [{ name: "Range Rover", count: 41 }, { name: "Defender", count: 88 }, { name: "Discovery", count: 70 }, { name: "Evoque", count: 71 }] },
  { make: "Honda", count: 120, models: [{ name: "CR-V", count: 84 }, { name: "Civic", count: 100 }, { name: "Accord", count: 60 }, { name: "Fit", count: 91 }] },
  { make: "Mazda", count: 90, models: [{ name: "CX-5", count: 93 }, { name: "Mazda3", count: 88 }, { name: "BT-50", count: 18 }] },
  { make: "Isuzu", count: 180, models: [{ name: "D-Max", count: 32 }, { name: "MU-X", count: 77 }] },
  { make: "Renault", count: 80, models: [{ name: "Duster", count: 91 }, { name: "Kwid", count: 13 }, { name: "Clio", count: 70 }] },
  { make: "Chevrolet", count: 70, models: [{ name: "Captiva", count: 68 }, { name: "Spark", count: 86 }, { name: "Cruze", count: 24 }] },
  { make: "Peugeot", count: 60, models: [{ name: "3008", count: 47 }, { name: "208", count: 105 }, { name: "508", count: 40 }] },
  { make: "Jeep", count: 85, models: [{ name: "Grand Cherokee", count: 80 }, { name: "Wrangler", count: 75 }, { name: "Compass", count: 58 }] },
  { make: "Subaru", count: 50, models: [{ name: "Forester", count: 81 }, { name: "Outback", count: 36 }, { name: "Impreza", count: 83 }] },
  { make: "Audi", count: 45, models: [{ name: "Q7", count: 45 }, { name: "Q5", count: 35 }, { name: "A4", count: 86 }] },
  { make: "Volvo", count: 40, models: [{ name: "XC90", count: 28 }, { name: "XC60", count: 79 }] },
  { make: "Porsche", count: 35, models: [{ name: "Cayenne", count: 13 }, { name: "Macan", count: 27 }, { name: "Panamera", count: 61 }] },
  { make: "Changan", count: 60, models: [{ name: "CS35", count: 74 }, { name: "CS75", count: 59 }, { name: "Alsvin", count: 104 }] },
  { make: "Haval", count: 65, models: [{ name: "H6", count: 24 }, { name: "Jolion", count: 24 }] },
  { make: "GWM", count: 55, models: [{ name: "P-Series", count: 61 }, { name: "Steed", count: 91 }] },
  { make: "JAC", count: 30, models: [{ name: "T8", count: 61 }, { name: "T6", count: 80 }] },
  { make: "Foton", count: 25, models: [{ name: "Tunland", count: 59 }] },
  { make: "BYD", count: 20, models: [{ name: "Atto 3", count: 89 }, { name: "Tang", count: 99 }] },
  { make: "Mahindra", count: 40, models: [{ name: "Scorpio", count: 103 }, { name: "Pik-Up", count: 92 }] }
];

export const PRICE_OPTIONS_CASH = [
  { value: "5000", label: "$5,000" },
  { value: "10000", label: "$10,000" },
  { value: "20000", label: "$20,000" },
  { value: "50000", label: "$50,000" },
  { value: "100000", label: "$100,000" },
];

export const PRICE_OPTIONS_MONTHLY = [
  { value: "100", label: "$100/mo" },
  { value: "250", label: "$250/mo" },
  { value: "500", label: "$500/mo" },
  { value: "1000", label: "$1,000/mo" },
];

export const YEAR_OPTIONS = [
  { value: "2010", label: "2010" },
  { value: "2015", label: "2015" },
  { value: "2018", label: "2018" },
  { value: "2020", label: "2020" },
  { value: "2023", label: "2023" },
];
