export const PROVINCES = [
  { name: "Kinshasa" },
  { name: "Haut-Katanga" },
  { name: "Kongo Central" },
  { name: "Nord-Kivu" },
  { name: "Sud-Kivu" },
  { name: "Lualaba" },
  { name: "Ituri" },
  { name: "Tshopo" },
  { name: "Kasaï-Oriental" },
  { name: "Tanganyika" },
  { name: "Kasaï-Central" },
  { name: "Haut-Uélé" },
  { name: "Bas-Uélé" },
  { name: "Kasaï" },
  { name: "Haut-Lomami" },
  { name: "Kwilu" },
  { name: "Maniema" },
  { name: "Kwango" },
  { name: "Sud-Ubangi" },
  { name: "Lomami" },
  { name: "Nord-Ubangi" },
  { name: "Équateur" },
  { name: "Mongala" },
  { name: "Mai-Ndombe" },
  { name: "Sankuru" },
  { name: "Tshuapa" },
];

export const MAKES_AND_MODELS = [
  { make: "Acura", models: [{ name: "MDX" }, { name: "RDX" }, { name: "TLX" }, { name: "Integra" }, { name: "ILX" }] },
  { make: "Alfa Romeo", models: [{ name: "Stelvio" }, { name: "Giulia" }, { name: "Tonale" }, { name: "Giulietta" }, { name: "159" }] },
  { make: "Aston Martin", models: [{ name: "DBX" }, { name: "Vantage" }, { name: "DB11" }, { name: "DB9" }, { name: "DBS" }] },
  { make: "Audi", models: [{ name: "Q7" }, { name: "Q5" }, { name: "Q8" }, { name: "Q3" }, { name: "A4" }, { name: "A6" }, { name: "A3" }, { name: "A5" }, { name: "A8" }, { name: "e-tron" }, { name: "RS6" }] },
  { make: "BAIC", models: [{ name: "BJ40" }, { name: "BJ80" }, { name: "X35" }, { name: "X55" }, { name: "D20" }] },
  { make: "Bentley", models: [{ name: "Continental GT" }, { name: "Bentayga" }, { name: "Flying Spur" }, { name: "Mulsanne" }] },
  { make: "BMW", models: [{ name: "X5" }, { name: "X6" }, { name: "X3" }, { name: "X1" }, { name: "X7" }, { name: "3 Series" }, { name: "5 Series" }, { name: "7 Series" }, { name: "4 Series" }, { name: "1 Series" }, { name: "M3" }, { name: "M5" }, { name: "iX" }] },
  { make: "BYD", models: [{ name: "Song Plus" }, { name: "Tang" }, { name: "Han" }, { name: "Atto 3" }, { name: "Seal" }, { name: "Dolphin" }, { name: "Yuan Plus" }, { name: "F3" }] },
  { make: "Cadillac", models: [{ name: "Escalade" }, { name: "XT5" }, { name: "XT6" }, { name: "XT4" }, { name: "CT5" }, { name: "SRX" }] },
  { make: "Changan", models: [{ name: "CS35 Plus" }, { name: "CS55 Plus" }, { name: "CS75 Plus" }, { name: "CS85" }, { name: "CS95" }, { name: "UNI-T" }, { name: "UNI-K" }, { name: "UNI-V" }, { name: "Alsvin" }, { name: "Hunter" }] },
  { make: "Chery", models: [{ name: "Tiggo 2" }, { name: "Tiggo 4 Pro" }, { name: "Tiggo 7 Pro" }, { name: "Tiggo 8 Pro" }, { name: "Arrizo 5" }, { name: "Arrizo 6" }, { name: "Omoda 5" }] },
  { make: "Chevrolet", models: [{ name: "Tahoe" }, { name: "Suburban" }, { name: "Silverado" }, { name: "Captiva" }, { name: "Trailblazer" }, { name: "Equinox" }, { name: "Camaro" }, { name: "Spark" }, { name: "Cruze" }, { name: "Colorado" }] },
  { make: "Chrysler", models: [{ name: "300" }, { name: "Pacifica" }, { name: "Grand Voyager" }] },
  { make: "Citroën", models: [{ name: "C3" }, { name: "C3 Aircross" }, { name: "C4" }, { name: "C5 Aircross" }, { name: "Berlingo" }, { name: "Jumpy" }, { name: "C-Elysée" }] },
  { make: "Dacia", models: [{ name: "Duster" }, { name: "Sandero" }, { name: "Logan" }, { name: "Jogger" }] },
  { make: "Daihatsu", models: [{ name: "Terios" }, { name: "Sirion" }, { name: "Hijet" }, { name: "Rocky" }] },
  { make: "DFSK / Dongfeng", models: [{ name: "Glory 580" }, { name: "Glory 500" }, { name: "Rich 6" }, { name: "Fengon" }] },
  { make: "Dodge", models: [{ name: "RAM 1500" }, { name: "Durango" }, { name: "Charger" }, { name: "Challenger" }, { name: "Journey" }] },
  { make: "DS Automobiles", models: [{ name: "DS 7" }, { name: "DS 4" }, { name: "DS 3" }, { name: "DS 9" }] },
  { make: "Ferrari", models: [{ name: "488" }, { name: "F8 Tributo" }, { name: "Roma" }, { name: "Portofino" }, { name: "296 GTB" }, { name: "Purosangue" }] },
  { make: "Fiat", models: [{ name: "500" }, { name: "Tipo" }, { name: "Panda" }, { name: "Punto" }, { name: "Ducato" }, { name: "Strada" }] },
  { make: "Ford", models: [{ name: "Ranger" }, { name: "Everest" }, { name: "Explorer" }, { name: "Expedition" }, { name: "F-150" }, { name: "Edge" }, { name: "Escape" }, { name: "EcoSport" }, { name: "Mustang" }, { name: "Transit" }] },
  { make: "Foton", models: [{ name: "Tunland" }, { name: "View" }, { name: "Toano" }, { name: "Aumark" }] },
  { make: "Geely", models: [{ name: "Coolray" }, { name: "Azkarra" }, { name: "Tugella" }, { name: "Monjaro" }, { name: "Emgrand" }, { name: "Okavango" }] },
  { make: "Genesis", models: [{ name: "GV80" }, { name: "GV70" }, { name: "G80" }, { name: "G70" }, { name: "G90" }] },
  { make: "GMC", models: [{ name: "Yukon" }, { name: "Sierra" }, { name: "Acadia" }, { name: "Terrain" }, { name: "Canyon" }] },
  { make: "GWM", models: [{ name: "P-Series / Poer" }, { name: "Tank 300" }, { name: "Tank 500" }, { name: "Steed" }, { name: "Wingle" }] },
  { make: "Haval", models: [{ name: "H6" }, { name: "Jolion" }, { name: "H9" }, { name: "Dargo" }, { name: "H2" }] },
  { make: "Hino", models: [{ name: "300 Series" }, { name: "500 Series" }, { name: "700 Series" }] },
  { make: "Honda", models: [{ name: "CR-V" }, { name: "Civic" }, { name: "Accord" }, { name: "HR-V" }, { name: "Pilot" }, { name: "Fit / Jazz" }, { name: "Passport" }, { name: "City" }] },
  { make: "Hongqi", models: [{ name: "H5" }, { name: "H9" }, { name: "HS5" }, { name: "HS7" }, { name: "E-HS9" }] },
  { make: "Hyundai", models: [{ name: "Tucson" }, { name: "Santa Fe" }, { name: "Creta" }, { name: "Elantra" }, { name: "Accent" }, { name: "Palisade" }, { name: "Kona" }, { name: "Venue" }, { name: "Sonata" }, { name: "Staria" }, { name: "H-100" }] },
  { make: "Infiniti", models: [{ name: "QX80" }, { name: "QX60" }, { name: "QX50" }, { name: "Q50" }, { name: "QX70" }] },
  { make: "Isuzu", models: [{ name: "D-Max" }, { name: "MU-X" }, { name: "N-Series / Elf" }, { name: "F-Series" }, { name: "Trooper" }] },
  { make: "Iveco", models: [{ name: "Daily" }, { name: "Eurocargo" }, { name: "Stralis" }, { name: "T-Way" }] },
  { make: "JAC", models: [{ name: "T8" }, { name: "T8 Pro" }, { name: "T6" }, { name: "T9" }, { name: "JS4" }, { name: "Sunray" }] },
  { make: "Jaecoo", models: [{ name: "J7" }, { name: "J8" }] },
  { make: "Jaguar", models: [{ name: "F-Pace" }, { name: "E-Pace" }, { name: "I-Pace" }, { name: "XF" }, { name: "XE" }, { name: "F-Type" }] },
  { make: "Jeep", models: [{ name: "Grand Cherokee" }, { name: "Wrangler" }, { name: "Gladiator" }, { name: "Compass" }, { name: "Renegade" }] },
  { make: "Jetour", models: [{ name: "Dashing" }, { name: "X70" }, { name: "X70 Plus" }, { name: "X90" }, { name: "Traveller / T2" }] },
  { make: "Kia", models: [{ name: "Sportage" }, { name: "Sorento" }, { name: "Seltos" }, { name: "Telluride" }, { name: "Picanto" }, { name: "Rio" }, { name: "Cerato" }, { name: "Carnival" }, { name: "K5" }, { name: "Sonet" }, { name: "Soul" }] },
  { make: "Lamborghini", models: [{ name: "Urus" }, { name: "Huracán" }, { name: "Aventador" }, { name: "Revuelto" }] },
  { make: "Land Rover", models: [{ name: "Range Rover" }, { name: "Range Rover Sport" }, { name: "Defender" }, { name: "Discovery" }, { name: "Range Rover Velar" }, { name: "Range Rover Evoque" }, { name: "Discovery Sport" }] },
  { make: "Lexus", models: [{ name: "LX 600" }, { name: "LX 570" }, { name: "GX 460" }, { name: "GX 550" }, { name: "RX 350" }, { name: "RX 500h" }, { name: "NX 300" }, { name: "TX" }, { name: "ES 350" }, { name: "IS 250" }] },
  { make: "Lincoln", models: [{ name: "Navigator" }, { name: "Aviator" }, { name: "Nautilus" }, { name: "Corsair" }] },
  { make: "Mahindra", models: [{ name: "Scorpio" }, { name: "Scorpio-N" }, { name: "XUV700" }, { name: "XUV300" }, { name: "Thar" }, { name: "Pik-Up" }, { name: "Bolero" }] },
  { make: "Maserati", models: [{ name: "Levante" }, { name: "Ghibli" }, { name: "Grecale" }, { name: "Quattroporte" }] },
  { make: "Maxus", models: [{ name: "T60" }, { name: "T90" }, { name: "V80" }, { name: "D90" }] },
  { make: "Mazda", models: [{ name: "CX-5" }, { name: "CX-30" }, { name: "CX-60" }, { name: "CX-90" }, { name: "CX-9" }, { name: "Mazda3" }, { name: "Mazda6" }, { name: "BT-50" }] },
  { make: "Mercedes-Benz", models: [{ name: "G-Class / G-Wagon" }, { name: "GLE" }, { name: "GLC" }, { name: "GLS" }, { name: "GLA" }, { name: "GLB" }, { name: "C-Class" }, { name: "E-Class" }, { name: "S-Class" }, { name: "CLA" }, { name: "CLS" }, { name: "Sprinter" }, { name: "Vito" }, { name: "V-Class" }] },
  { make: "MG", models: [{ name: "ZS" }, { name: "HS" }, { name: "RX5" }, { name: "MG GT" }, { name: "MG4" }, { name: "MG5" }] },
  { make: "MINI", models: [{ name: "Cooper" }, { name: "Countryman" }, { name: "Clubman" }] },
  { make: "Mitsubishi", models: [{ name: "Pajero" }, { name: "Pajero Sport" }, { name: "L200 / Triton" }, { name: "Outlander" }, { name: "ASX" }, { name: "Eclipse Cross" }, { name: "Xpander" }, { name: "Canter" }] },
  { make: "Nissan", models: [{ name: "Patrol" }, { name: "X-Trail" }, { name: "Navara" }, { name: "Hardbody" }, { name: "Pathfinder" }, { name: "Qashqai" }, { name: "Kicks" }, { name: "Juke" }, { name: "Sunny" }, { name: "Sentra" }, { name: "Urvan" }, { name: "Civilian" }] },
  { make: "Omoda", models: [{ name: "C5" }, { name: "O5" }, { name: "E5" }] },
  { make: "Opel", models: [{ name: "Corsa" }, { name: "Astra" }, { name: "Mokka" }, { name: "Grandland" }, { name: "Crossland" }, { name: "Combo" }] },
  { make: "Peugeot", models: [{ name: "3008" }, { name: "2008" }, { name: "5008" }, { name: "208" }, { name: "308" }, { name: "508" }, { name: "Landtrek" }, { name: "Partner" }, { name: "Boxer" }] },
  { make: "Porsche", models: [{ name: "Cayenne" }, { name: "Macan" }, { name: "Panamera" }, { name: "911" }, { name: "Taycan" }] },
  { make: "RAM", models: [{ name: "1500" }, { name: "2500" }, { name: "3500" }, { name: "TRX" }, { name: "ProMaster" }] },
  { make: "Renault", models: [{ name: "Duster" }, { name: "Koleos" }, { name: "Captur" }, { name: "Kwid" }, { name: "Clio" }, { name: "Megane" }, { name: "Triber" }, { name: "Master" }, { name: "Trafic" }] },
  { make: "Rolls-Royce", models: [{ name: "Cullinan" }, { name: "Ghost" }, { name: "Phantom" }, { name: "Wraith" }] },
  { make: "Scania", models: [{ name: "R-Series" }, { name: "G-Series" }, { name: "P-Series" }] },
  { make: "Seat", models: [{ name: "Ibiza" }, { name: "Leon" }, { name: "Arona" }, { name: "Ateca" }] },
  { make: "Skoda", models: [{ name: "Octavia" }, { name: "Superb" }, { name: "Kodiaq" }, { name: "Karoq" }] },
  { make: "SsangYong", models: [{ name: "Rexton" }, { name: "Musso" }, { name: "Korando" }, { name: "Tivoli" }] },
  { make: "Subaru", models: [{ name: "Forester" }, { name: "Outback" }, { name: "Crosstrek / XV" }, { name: "Impreza" }, { name: "WRX" }, { name: "Ascent" }] },
  { make: "Suzuki", models: [{ name: "Grand Vitara" }, { name: "Jimny" }, { name: "Swift" }, { name: "Vitara" }, { name: "Baleno" }, { name: "S-Presso" }, { name: "Ertiga" }, { name: "Celerio" }, { name: "Carry" }] },
  { make: "Tank", models: [{ name: "Tank 300" }, { name: "Tank 500" }] },
  { make: "Tata", models: [{ name: "Harrier" }, { name: "Safari" }, { name: "Nexon" }, { name: "Xenon" }, { name: "Prima" }] },
  { make: "Tesla", models: [{ name: "Model Y" }, { name: "Model 3" }, { name: "Model X" }, { name: "Model S" }, { name: "Cybertruck" }] },
  { make: "Toyota", models: [
    { name: "Land Cruiser" }, { name: "Land Cruiser Prado" }, { name: "Hilux" }, { name: "Fortuner" }, 
    { name: "RAV4" }, { name: "Corolla" }, { name: "Camry" }, { name: "Yaris" }, 
    { name: "Highlander" }, { name: "HiAce" }, { name: "Coaster" }, { name: "4Runner" }, 
    { name: "Tacoma" }, { name: "Tundra" }, { name: "Harrier" }, { name: "Vitz" }, 
    { name: "Rush" }, { name: "Sienna" }, { name: "Alphard" }, { name: "Crown" }, 
    { name: "Sequoia" }, { name: "Prius" }, { name: "FJ Cruiser" }, { name: "Urban Cruiser" }, 
    { name: "Starlet" }, { name: "Rumion" }, { name: "Land Cruiser 70 Series" }
  ] },
  { make: "Volkswagen", models: [{ name: "Touareg" }, { name: "Tiguan" }, { name: "Golf" }, { name: "Polo" }, { name: "Amarok" }, { name: "Passat" }, { name: "T-Cross" }, { name: "Teramont / Atlas" }, { name: "Crafter" }, { name: "Transporter" }, { name: "ID.4" }] },
  { make: "Volvo", models: [{ name: "XC90" }, { name: "XC60" }, { name: "XC40" }, { name: "EX90" }, { name: "EX30" }, { name: "S90" }, { name: "S60" }] },
  { make: "Zeekr", models: [{ name: "001" }, { name: "009" }, { name: "X" }] }
];

export const PRICE_OPTIONS_CASH = [
  { value: "5000", label: "$5,000" },
  { value: "10000", label: "$10,000" },
  { value: "20000", label: "$20,000" },
  { value: "50000", label: "$50,000" },
  { value: "100000", label: "$100,000" },
];

export const PRICE_OPTIONS_MONTHLY = [
  { value: "100", label: "$100/mo" },
  { value: "250", label: "$250/mo" },
  { value: "500", label: "$500/mo" },
  { value: "1000", label: "$1,000/mo" },
];

export const YEAR_OPTIONS = [
  { value: "2010", label: "2010" },
  { value: "2015", label: "2015" },
  { value: "2018", label: "2018" },
  { value: "2020", label: "2020" },
  { value: "2023", label: "2023" },
];
