export const PROVINCES = [
  { name: "Kinshasa" },
  { name: "Haut-Katanga" },
  { name: "Kongo Central" },
  { name: "Nord-Kivu" },
  { name: "Sud-Kivu" },
  { name: "Lualaba" },
  { name: "Ituri" },
  { name: "Tshopo" },
  { name: "Kasaï-Oriental" },
  { name: "Tanganyika" },
  { name: "Kasaï-Central" },
  { name: "Haut-Uélé" },
  { name: "Bas-Uélé" },
  { name: "Kasaï" },
  { name: "Haut-Lomami" },
  { name: "Kwilu" },
  { name: "Maniema" },
  { name: "Kwango" },
  { name: "Sud-Ubangi" },
  { name: "Lomami" },
  { name: "Nord-Ubangi" },
  { name: "Équateur" },
  { name: "Mongala" },
  { name: "Mai-Ndombe" },
  { name: "Sankuru" },
  { name: "Tshuapa" },
];

export const MAKES_AND_MODELS = [
  { make: "Toyota", models: [{ name: "Corolla" }, { name: "RAV4" }, { name: "Land Cruiser" }, { name: "Hilux" }, { name: "Camry" }, { name: "Yaris" }, { name: "Prado" }, { name: "Fortuner" }] },
  { make: "Mercedes-Benz", models: [{ name: "C-Class" }, { name: "E-Class" }, { name: "G-Class" }, { name: "GLE" }, { name: "GLC" }] },
  { make: "Ford", models: [{ name: "Ranger" }, { name: "Figo" }, { name: "Everest" }, { name: "F-150" }, { name: "EcoSport" }] },
  { make: "Hyundai", models: [{ name: "Tucson" }, { name: "Santa Fe" }, { name: "Elantra" }, { name: "Creta" }, { name: "Accent" }] },
  { make: "Nissan", models: [{ name: "Patrol" }, { name: "X-Trail" }, { name: "Navara" }, { name: "Hardbody" }, { name: "Almera" }] },
  { make: "Mitsubishi", models: [{ name: "Pajero" }, { name: "L200" }, { name: "Outlander" }, { name: "ASX" }] },
  { make: "Kia", models: [{ name: "Sportage" }, { name: "Sorento" }, { name: "Picanto" }, { name: "Rio" }] },
  { make: "BMW", models: [{ name: "X5" }, { name: "3 Series" }, { name: "X3" }, { name: "5 Series" }] },
  { make: "Volkswagen", models: [{ name: "Touareg" }, { name: "Golf" }, { name: "Tiguan" }, { name: "Polo" }, { name: "Amarok" }] },
  { make: "Lexus", models: [{ name: "RX 350" }, { name: "LX 570" }, { name: "IS 250" }, { name: "GX 460" }] },
  { make: "Suzuki", models: [{ name: "Grand Vitara" }, { name: "Swift" }, { name: "Jimny" }, { name: "Alto" }] },
  { make: "Land Rover", models: [{ name: "Range Rover" }, { name: "Defender" }, { name: "Discovery" }, { name: "Evoque" }] },
  { make: "Honda", models: [{ name: "CR-V" }, { name: "Civic" }, { name: "Accord" }, { name: "Fit" }] },
  { make: "Mazda", models: [{ name: "CX-5" }, { name: "Mazda3" }, { name: "BT-50" }] },
  { make: "Isuzu", models: [{ name: "D-Max" }, { name: "MU-X" }] },
  { make: "Renault", models: [{ name: "Duster" }, { name: "Kwid" }, { name: "Clio" }] },
  { make: "Chevrolet", models: [{ name: "Captiva" }, { name: "Spark" }, { name: "Cruze" }] },
  { make: "Peugeot", models: [{ name: "3008" }, { name: "208" }, { name: "508" }] },
  { make: "Jeep", models: [{ name: "Grand Cherokee" }, { name: "Wrangler" }, { name: "Compass" }] },
  { make: "Subaru", models: [{ name: "Forester" }, { name: "Outback" }, { name: "Impreza" }] },
  { make: "Audi", models: [{ name: "Q7" }, { name: "Q5" }, { name: "A4" }] },
  { make: "Volvo", models: [{ name: "XC90" }, { name: "XC60" }] },
  { make: "Porsche", models: [{ name: "Cayenne" }, { name: "Macan" }, { name: "Panamera" }] },
  { make: "Changan", models: [{ name: "CS35" }, { name: "CS75" }, { name: "Alsvin" }] },
  { make: "Haval", models: [{ name: "H6" }, { name: "Jolion" }] },
  { make: "GWM", models: [{ name: "P-Series" }, { name: "Steed" }] },
  { make: "JAC", models: [{ name: "T8" }, { name: "T6" }] },
  { make: "Foton", models: [{ name: "Tunland" }] },
  { make: "BYD", models: [{ name: "Atto 3" }, { name: "Tang" }] },
  { make: "Mahindra", models: [{ name: "Scorpio" }, { name: "Pik-Up" }] }
];

export const PRICE_OPTIONS_CASH = [
  { value: "5000", label: "$5,000" },
  { value: "10000", label: "$10,000" },
  { value: "20000", label: "$20,000" },
  { value: "50000", label: "$50,000" },
  { value: "100000", label: "$100,000" },
];

export const PRICE_OPTIONS_MONTHLY = [
  { value: "100", label: "$100/mo" },
  { value: "250", label: "$250/mo" },
  { value: "500", label: "$500/mo" },
  { value: "1000", label: "$1,000/mo" },
];

export const YEAR_OPTIONS = [
  { value: "2010", label: "2010" },
  { value: "2015", label: "2015" },
  { value: "2018", label: "2018" },
  { value: "2020", label: "2020" },
  { value: "2023", label: "2023" },
];
